version: "3.9"
services:
  web:
    build: .
    ports:
      - "5173:5173"
    environment:
      - GANACHE_URL=http://ganache:8545
    depends_on:
      ganache:
        condition: service_started
      pocketbase:
        condition: service_healthy
  ganache:
    image: "trufflesuite/ganache:latest"
    ports:
      - "8545:8545"
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./frontend/pocketbase/pb_data:/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
