name: test-contracts
on: [push]
jobs:
  test-contracts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      # - name: Compile Reach contracts
      #   run: ./reach compile app/index.rsh -o app/build
      - name: Install dependencies
        run: pnpm install
      # - name: Compile hardhat contracts
      #   run: pnpm -C contracts/ethereum compile
      - name: Run tests
        run: pnpm -C contracts/ethereum test
